spring:
  application:
    name: Loja-Produtos
  datasource:
    url: jdbc:h2:mem:produtodb
    driver-class-name: org.h2.Driver
    username: produto
    password: produto
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
#  web:
#    resources:
#      static-locations: classpath:/META-INF/resources/, classpath:/resources/, classpath:/static/, classpath:/public/

flyway:
  enabled: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
#    path: /swagger-ui/index.html
#    operationsSorter: method
#    tagsSorter: name